### ISSUE TITLE
Add more feature

### ISSUE THREAD

**Issue by LW-Ho** [faithcsc/auto-neopets#1]
Hello, I suggest you add other functions. I have the modified repository here for your reference.
In the future I plan to integrate training schools.

https://github.com/LW-Ho/NeopetHelper

**Comment by faithcsc** [comment]
Hi @LW-Ho I appreciate your interest, however as I have no capacity to maintain this project I'll be archiving it. Feel free to make a fork and incorporate your changes and I'll be happy to link to your fork if you wish.
